// Generated by CodiumAI
import isPalindrome from '../LongestPalindrome';

describe('isPalindrome', () => {

    // Returns true for a single character string
    it('should return true when given a single character string', () => {
        expect(isPalindrome('a')).toBe(true);
    });

    // Returns false for a non-palindrome string with even length
    it('should return false when given a non-palindrome string with even length', () => {
        expect(isPalindrome('hello')).toBe(false);
    });

    it('should return true when given a long palindrome string', () => {
        expect(isPalindrome('mattam')).toBe(true);
    });
});
